name: moyennesed
description: Une application qui permet aux élèves de voir leurs moyennes ÉcoleDirecte.
publish_to: "none"
version: 2.0.8+3

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cloud_firestore: ^4.8.1
  firebase_app_check: ^0.1.4+3
  firebase_core: ^2.14.0
  fluentui_system_icons: ^1.1.200
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  gap: ^3.0.0
  http: ^0.13.6
  localstorage: ^4.0.1+2
  lottie: ^2.3.2
  modal_bottom_sheet: ^2.1.2
  path_provider: ^2.0.14
  provider: ^6.0.5
  url_launcher: ^6.1.11

flutter_native_splash:
  color: '#ffffff'
  ios: true
  image: assets/splash_screen.jpg

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: Bitter
      fonts:
        - asset: assets/fonts/Bitter-Regular.ttf
