import 'package:moyennesed/core/handlers/file_handler.dart';
import 'package:moyennesed/core/objects/period.dart';

// All the known informations about the student //
class StudentInfos {
  static int id = 0;

  static String firstName = "";
  static String lastName = "";
  static String get fullName => "$firstName $lastName";

  static String level = "";
  static String gender = "";
  
  static String email = "";
  static String phone = "";

  static void saveLoginData(Map loginData) {
    id = loginData["id"];

    firstName = loginData["prenom"];
    lastName = loginData["nom"];

    level = loginData["profile"]["classe"]["libelle"];
    gender = loginData["profile"]["sexe"];
    
    email = loginData["modules"][5]["params"]["mailPerso"];
    phone = loginData["profile"]["telPortable"].replaceAll("-", " ");
  }
}

// All the calculated informations like grades and averages //
class GlobalInfos {
  static final Map<String, Period> periods = <String, Period>{};
  static Period addPeriod(Map jsonInfos) {
    Period period = Period();
    period.init(jsonInfos);
    periods.addAll({period.code: period});
    return period;
  }
}

// The informations modifiable by the user //
class ModifiableInfos {
  static bool useSubjectCoefficients = true;
  static bool guessGradeCoefficient = true;
  
  static Map<String, double> subjectCoefficients = <String, double>{
    "FRANC": 3.0,
    "HI-GE": 3.0,
    "AGL1": 3.0,
    "ESP2": 2.0,
    "ALL2": 2.0,
    "SES": 2.0,
    "MATHS": 3.0,
    "PH-CH": 2.0,
    "SVT": 2.0,
    "SNTEC": 1.0,
    "EPS": 2.0,
  };

  // Function to locally save these informations //
  static Future<void> save() async {
    await FileHandler.instance.changeInfos({
      "guess_grade_coef": guessGradeCoefficient,
      "use_subject_coef": useSubjectCoefficients
    });
  }
}

// DEMO ACCOUNT
class DemoAccount {
  static const Map<String, dynamic> demoAccountInfos = {
    "username": "demo",
    "password": "1234",

    "id": 0,
    "prenom": "DEMO",
    "nom": "ACCOUNT",
    "profile": {
      "classe": {
        "libelle": "Demo level"
      },
      "sexe": "M",
      "telPortable": "00-00-00-00-00"
    },
    "modules": {
      5: {
        "params": {
          "mailPerso": "demoaccount@laroche.org"
        }
      }
    }
  };
  static const Map<String, dynamic> demoAccountGrades = {
    "periodes": {
      0: {
        "codePeriode": "A001",
        "periode": "1er Trimestre",
        "cloture": true,
        "ensembleMatieres": {
          "nomPP": "Un professeur quelconque",
          "disciplines": [
              {
                  "codeMatiere": "FRANC",
                  "discipline": "FRANCAIS",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 0,
                          "nom": "Un professeur quelconque"
                      },
                  ]
              },
              {
                  "codeMatiere": "HI-GE",
                  "discipline": "HISTOIRE-GEOGRAPHIE",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 1,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              },
              {
                  "codeMatiere": "AGL1",
                  "discipline": "ANGLAIS LV1",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 214,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              },
              {
                  "codeMatiere": "ESP2",
                  "discipline": "ESPAGNOL LV2",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 318,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              },
              {
                  "codeMatiere": "SES",
                  "discipline": "SC. ECONO.& SOCIALES",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 320,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              },
              {
                  "codeMatiere": "MATHS",
                  "discipline": "MATHEMATIQUES",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 59,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              },
              {
                  "codeMatiere": "PH-CH",
                  "discipline": "PHYSIQUE-CHIMIE",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 86,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              },
              {
                  "codeMatiere": "SVT",
                  "discipline": "SCIENCES VIE & TERRE",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 60,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              },
              {
                  "codeMatiere": "SNTEC",
                  "discipline": "SC.NUMERIQ.TECHNOL.",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 59,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              },
              {
                  "codeMatiere": "EPS",
                  "discipline": "ED.PHYSIQUE & SPORT.",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 97,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              },
              {
                  "codeMatiere": "LCALA",
                  "discipline": "LCA LATIN",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 25,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              }
          ]
        }
      },
      3: {
        "codePeriode": "A002",
        "periode": "2e Trimestre",
        "cloture": false,
        "ensembleMatieres": {
          "nomPP": "Un professeur quelconque",
          "disciplines": [
              {
                  "codeMatiere": "FRANC",
                  "discipline": "FRANCAIS",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 0,
                          "nom": "Un professeur quelconque"
                      },
                  ]
              },
              {
                  "codeMatiere": "HI-GE",
                  "discipline": "HISTOIRE-GEOGRAPHIE",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 1,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              },
              {
                  "codeMatiere": "AGL1",
                  "discipline": "ANGLAIS LV1",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 214,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              },
              {
                  "codeMatiere": "ESP2",
                  "discipline": "ESPAGNOL LV2",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 318,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              },
              {
                  "codeMatiere": "SES",
                  "discipline": "SC. ECONO.& SOCIALES",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 320,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              },
              {
                  "codeMatiere": "MATHS",
                  "discipline": "MATHEMATIQUES",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 59,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              },
              {
                  "codeMatiere": "PH-CH",
                  "discipline": "PHYSIQUE-CHIMIE",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 86,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              },
              {
                  "codeMatiere": "SVT",
                  "discipline": "SCIENCES VIE & TERRE",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 60,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              },
              {
                  "codeMatiere": "SNTEC",
                  "discipline": "SC.NUMERIQ.TECHNOL.",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 59,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              },
              {
                  "codeMatiere": "EPS",
                  "discipline": "ED.PHYSIQUE & SPORT.",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 97,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              },
              {
                  "codeMatiere": "LCALA",
                  "discipline": "LCA LATIN",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 25,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              }
          ]
        }
      },
      6: {
        "codePeriode": "A003",
        "periode": "3e Trimestre",
        "cloture": false,
        "ensembleMatieres": {
          "nomPP": "Un professeur quelconque",
          "disciplines": [
              {
                  "codeMatiere": "FRANC",
                  "discipline": "FRANCAIS",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 0,
                          "nom": "Un professeur quelconque"
                      },
                  ]
              },
              {
                  "codeMatiere": "HI-GE",
                  "discipline": "HISTOIRE-GEOGRAPHIE",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 1,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              },
              {
                  "codeMatiere": "AGL1",
                  "discipline": "ANGLAIS LV1",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 214,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              },
              {
                  "codeMatiere": "ESP2",
                  "discipline": "ESPAGNOL LV2",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 318,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              },
              {
                  "codeMatiere": "SES",
                  "discipline": "SC. ECONO.& SOCIALES",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 320,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              },
              {
                  "codeMatiere": "MATHS",
                  "discipline": "MATHEMATIQUES",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 59,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              },
              {
                  "codeMatiere": "PH-CH",
                  "discipline": "PHYSIQUE-CHIMIE",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 86,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              },
              {
                  "codeMatiere": "SVT",
                  "discipline": "SCIENCES VIE & TERRE",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 60,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              },
              {
                  "codeMatiere": "SNTEC",
                  "discipline": "SC.NUMERIQ.TECHNOL.",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 59,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              },
              {
                  "codeMatiere": "EPS",
                  "discipline": "ED.PHYSIQUE & SPORT.",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 97,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              },
              {
                  "codeMatiere": "LCALA",
                  "discipline": "LCA LATIN",
                  "coef": 0,
                  "professeurs": [
                      {
                          "id": 25,
                          "nom": "Un professeur quelconque"
                      }
                  ]
              }
          ]
        }
      },
    },
    "notes": [
      {
        "id": 20971522,
        "devoir": "TP dessin paramécie",
        "codePeriode": "A001",
        "codeMatiere": "SVT",
        "libelleMatiere": "SCIENCES VIE & TERRE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "10",
        "valeur": "9,5",
        "nonSignificatif": false,
        "date": "2022-09-05",
        "dateSaisie": "2022-09-12",
        "valeurisee": false,
        "moyenneClasse": "7.96",
        "elementsProgramme": []
      },
      {
        "id": 20971595,
        "devoir": "TP 1 chapitre 1",
        "codePeriode": "A001",
        "codeMatiere": "PH-CH",
        "libelleMatiere": "PHYSIQUE-CHIMIE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "13,5",
        "nonSignificatif": false,
        "date": "2022-09-12",
        "dateSaisie": "2022-09-20",
        "valeurisee": false,
        "moyenneClasse": "14.20",
        "elementsProgramme": []
      },
      {
        "id": 20971564,
        "devoir": "Dictée: Incipit de l'Education Sentimentale",
        "codePeriode": "A001",
        "codeMatiere": "FRANC",
        "libelleMatiere": "FRANCAIS",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "19,5",
        "nonSignificatif": false,
        "date": "2022-09-15",
        "dateSaisie": "2022-09-15",
        "valeurisee": false,
        "moyenneClasse": "10.30",
        "elementsProgramme": []
      },
      {
        "id": 20971704,
        "devoir": "TP 2 chapitre 1",
        "codePeriode": "A001",
        "codeMatiere": "PH-CH",
        "libelleMatiere": "PHYSIQUE-CHIMIE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "17",
        "nonSignificatif": false,
        "date": "2022-09-19",
        "dateSaisie": "2022-09-27",
        "valeurisee": false,
        "moyenneClasse": "14.89",
        "elementsProgramme": []
      },
      {
        "id": 20971633,
        "devoir": "DM 1",
        "codePeriode": "A001",
        "codeMatiere": "MATHS",
        "libelleMatiere": "MATHEMATIQUES",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "20",
        "nonSignificatif": false,
        "date": "2022-09-22",
        "dateSaisie": "2022-09-22",
        "valeurisee": false,
        "moyenneClasse": "18.43",
        "elementsProgramme": []
      },
      {
        "id": 20971857,
        "devoir": "IE",
        "codePeriode": "A001",
        "codeMatiere": "MATHS",
        "libelleMatiere": "MATHEMATIQUES",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "16",
        "nonSignificatif": false,
        "date": "2022-09-22",
        "dateSaisie": "2022-10-06",
        "valeurisee": false,
        "moyenneClasse": "11.61",
        "elementsProgramme": []
      },
      {
        "id": 20971667,
        "devoir": "Contrôle chapitre 0",
        "codePeriode": "A001",
        "codeMatiere": "PH-CH",
        "libelleMatiere": "PHYSIQUE-CHIMIE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "17",
        "nonSignificatif": false,
        "date": "2022-09-23",
        "dateSaisie": "2022-09-26",
        "valeurisee": false,
        "moyenneClasse": "13.96",
        "elementsProgramme": []
      },
      {
        "id": 20972032,
        "devoir": "CE Flop Top",
        "codePeriode": "A001",
        "codeMatiere": "AGL1",
        "libelleMatiere": "ANGLAIS LV1",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "13",
        "nonSignificatif": false,
        "date": "2022-09-26",
        "dateSaisie": "2022-10-10",
        "valeurisee": false,
        "moyenneClasse": "9.63",
        "elementsProgramme": []
      },
      {
        "id": 20972033,
        "devoir": "EE Flop Top",
        "codePeriode": "A001",
        "codeMatiere": "AGL1",
        "libelleMatiere": "ANGLAIS LV1",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "17",
        "nonSignificatif": false,
        "date": "2022-09-26",
        "dateSaisie": "2022-10-10",
        "valeurisee": false,
        "moyenneClasse": "11.58",
        "elementsProgramme": []
      },
      {
        "id": 20972049,
        "devoir": "EE - Séquence 1 : Mi autorretrato ",
        "codePeriode": "A001",
        "codeMatiere": "ESP2",
        "libelleMatiere": "ESPAGNOL LV2",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "14",
        "nonSignificatif": false,
        "date": "2022-09-29",
        "dateSaisie": "2022-10-09",
        "valeurisee": false,
        "moyenneClasse": "13.20",
        "elementsProgramme": []
      },
      {
        "id": 20971783,
        "devoir": "Oral",
        "codePeriode": "A001",
        "codeMatiere": "HI-GE",
        "libelleMatiere": "HISTOIRE-GEOGRAPHIE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "14",
        "nonSignificatif": false,
        "date": "2022-09-30",
        "dateSaisie": "2022-09-30",
        "valeurisee": false,
        "moyenneClasse": "13.50",
        "elementsProgramme": []
      },
      {
        "id": 20972214,
        "devoir": "DST n° 1",
        "codePeriode": "A001",
        "codeMatiere": "PH-CH",
        "libelleMatiere": "PHYSIQUE-CHIMIE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "16,5",
        "nonSignificatif": false,
        "date": "2022-10-11",
        "dateSaisie": "2022-10-17",
        "valeurisee": false,
        "moyenneClasse": "11.26",
        "elementsProgramme": []
      },
      {
        "id": 20972923,
        "devoir": "Volley",
        "codePeriode": "A001",
        "codeMatiere": "EPS",
        "libelleMatiere": "ED.PHYSIQUE & SPORT.",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "14",
        "nonSignificatif": false,
        "date": "2022-10-11",
        "dateSaisie": "2022-11-23",
        "valeurisee": false,
        "moyenneClasse": "14.53",
        "elementsProgramme": []
      },
      {
        "id": 20972111,
        "devoir": "Evaluation de lectures DST",
        "codePeriode": "A001",
        "codeMatiere": "FRANC",
        "libelleMatiere": "FRANCAIS",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "12",
        "nonSignificatif": false,
        "date": "2022-10-11",
        "dateSaisie": "2022-10-11",
        "valeurisee": false,
        "moyenneClasse": "15.26",
        "elementsProgramme": []
      },
      {
        "id": 20972113,
        "devoir": "DST PARTIE 2 : sujet d'écriture.",
        "codePeriode": "A001",
        "codeMatiere": "FRANC",
        "libelleMatiere": "FRANCAIS",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "14",
        "nonSignificatif": false,
        "date": "2022-10-11",
        "dateSaisie": "2022-10-11",
        "valeurisee": false,
        "moyenneClasse": "11.29",
        "elementsProgramme": []
      },
      {
        "id": 20972115,
        "devoir": "Exposé en binôme: thèmes de la séquence;",
        "codePeriode": "A001",
        "codeMatiere": "FRANC",
        "libelleMatiere": "FRANCAIS",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "14",
        "nonSignificatif": false,
        "date": "2022-10-11",
        "dateSaisie": "2022-10-11",
        "valeurisee": false,
        "moyenneClasse": "15.26",
        "elementsProgramme": []
      },
      {
        "id": 20972114,
        "devoir": "Evaluation sur la poésie",
        "codePeriode": "A001",
        "codeMatiere": "FRANC",
        "libelleMatiere": "FRANCAIS",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "14,5",
        "nonSignificatif": false,
        "date": "2022-10-11",
        "dateSaisie": "2022-10-11",
        "valeurisee": false,
        "moyenneClasse": "15.15",
        "elementsProgramme": []
      },
      {
        "id": 20972090,
        "devoir": "Evaluation sur les courants littéraires",
        "codePeriode": "A001",
        "codeMatiere": "FRANC",
        "libelleMatiere": "FRANCAIS",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "12",
        "nonSignificatif": false,
        "date": "2022-10-11",
        "dateSaisie": "2022-10-11",
        "valeurisee": false,
        "moyenneClasse": "13.09",
        "elementsProgramme": []
      },
      {
        "id": 20972379,
        "devoir": "DS",
        "codePeriode": "A001",
        "codeMatiere": "MATHS",
        "libelleMatiere": "MATHEMATIQUES",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "16",
        "nonSignificatif": false,
        "date": "2022-10-11",
        "dateSaisie": "2022-11-08",
        "valeurisee": false,
        "moyenneClasse": "9.87",
        "elementsProgramme": []
      },
      {
        "id": 20972406,
        "devoir": "TF#1 FLOP TOP",
        "codePeriode": "A001",
        "codeMatiere": "AGL1",
        "libelleMatiere": "ANGLAIS LV1",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "13",
        "nonSignificatif": false,
        "date": "2022-10-17",
        "dateSaisie": "2022-11-08",
        "valeurisee": false,
        "moyenneClasse": "12.27",
        "elementsProgramme": []
      },
      {
        "id": 20972267,
        "devoir": "DM 2",
        "codePeriode": "A001",
        "codeMatiere": "MATHS",
        "libelleMatiere": "MATHEMATIQUES",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "20",
        "nonSignificatif": false,
        "date": "2022-10-18",
        "dateSaisie": "2022-10-18",
        "valeurisee": false,
        "moyenneClasse": "18.43",
        "elementsProgramme": []
      },
      {
        "id": 20972362,
        "devoir": "Oral thèmes 1 et 2",
        "codePeriode": "A001",
        "codeMatiere": "SNTEC",
        "libelleMatiere": "SC.NUMERIQ.TECHNOL.",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "17,5",
        "nonSignificatif": false,
        "date": "2022-10-26",
        "dateSaisie": "2022-10-26",
        "valeurisee": false,
        "moyenneClasse": "16.03",
        "elementsProgramme": []
      },
      {
        "id": 20972374,
        "devoir": "DST sythèse",
        "codePeriode": "A001",
        "codeMatiere": "SVT",
        "libelleMatiere": "SCIENCES VIE & TERRE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "10",
        "valeur": "6,5",
        "nonSignificatif": false,
        "date": "2022-10-28",
        "dateSaisie": "2022-11-08",
        "valeurisee": false,
        "moyenneClasse": "6.38",
        "elementsProgramme": []
      },
      {
        "id": 20972373,
        "devoir": "DST QCM",
        "codePeriode": "A001",
        "codeMatiere": "SVT",
        "libelleMatiere": "SCIENCES VIE & TERRE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "10",
        "valeur": "8",
        "nonSignificatif": false,
        "date": "2022-10-28",
        "dateSaisie": "2022-11-08",
        "valeurisee": false,
        "moyenneClasse": "7.21",
        "elementsProgramme": []
      },
      {
        "id": 11,
        "devoir": "Evaluation CNED",
        "codePeriode": "A001",
        "codeMatiere": "ITA3H",
        "libelleMatiere": "ITALIEN LV3 HOR.ETAB",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "20",
        "nonSignificatif": false,
        "date": "2022-11-02",
        "dateSaisie": "2022-11-29",
        "valeurisee": false,
        "moyenneClasse": "20.00",
        "elementsProgramme": []
      },
      {
        "id": 12,
        "devoir": "Evaluation CNED",
        "codePeriode": "A001",
        "codeMatiere": "ITA3H",
        "libelleMatiere": "ITALIEN LV3 HOR.ETAB",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "20",
        "nonSignificatif": false,
        "date": "2022-11-04",
        "dateSaisie": "2022-11-29",
        "valeurisee": false,
        "moyenneClasse": "20.00",
        "elementsProgramme": []
      },
      {
        "id": 20972530,
        "devoir": "Oral : Deuxième séquence Sports et société",
        "codePeriode": "A001",
        "codeMatiere": "ESP2",
        "libelleMatiere": "ESPAGNOL LV2",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "14",
        "nonSignificatif": false,
        "date": "2022-11-08",
        "dateSaisie": "2022-11-14",
        "valeurisee": false,
        "moyenneClasse": "14.38",
        "elementsProgramme": [],
        "qcm": {
          "idQCM": 10,
          "idAssociation": 16,
          "titre": "Deporte y sociedad"
        }
      },
      {
        "id": 20972484,
        "devoir": "oral",
        "codePeriode": "A001",
        "codeMatiere": "MATHS",
        "libelleMatiere": "MATHEMATIQUES",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "20",
        "nonSignificatif": false,
        "date": "2022-11-10",
        "dateSaisie": "2022-11-11",
        "valeurisee": false,
        "moyenneClasse": "11.69",
        "elementsProgramme": []
      },
      {
        "id": 20972528,
        "devoir": "ORAUX",
        "codePeriode": "A001",
        "codeMatiere": "AGL1",
        "libelleMatiere": "ANGLAIS LV1",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "14",
        "nonSignificatif": false,
        "date": "2022-11-10",
        "dateSaisie": "2022-11-18",
        "valeurisee": false,
        "moyenneClasse": "12.25",
        "elementsProgramme": []
      },
      {
        "id": 20973030,
        "devoir": "COMPREHENSION ORALE",
        "codePeriode": "A001",
        "codeMatiere": "AGL1",
        "libelleMatiere": "ANGLAIS LV1",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "18",
        "nonSignificatif": false,
        "date": "2022-11-14",
        "dateSaisie": "2022-11-25",
        "valeurisee": false,
        "moyenneClasse": "13.41",
        "elementsProgramme": []
      },
      {
        "id": 20972660,
        "devoir": "Evaluation Athènes",
        "codePeriode": "A001",
        "codeMatiere": "HI-GE",
        "libelleMatiere": "HISTOIRE-GEOGRAPHIE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "10",
        "nonSignificatif": false,
        "date": "2022-11-17",
        "dateSaisie": "2022-11-17",
        "valeurisee": false,
        "moyenneClasse": "10.54",
        "elementsProgramme": []
      },
      {
        "id": 20972662,
        "devoir": "Oral",
        "codePeriode": "A001",
        "codeMatiere": "HI-GE",
        "libelleMatiere": "HISTOIRE-GEOGRAPHIE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "10",
        "nonSignificatif": false,
        "date": "2022-11-17",
        "dateSaisie": "2022-11-17",
        "valeurisee": false,
        "moyenneClasse": "13.64",
        "elementsProgramme": []
      },
      {
        "id": 20972761,
        "devoir": "Exposé Lisbonne",
        "codePeriode": "A001",
        "codeMatiere": "HI-GE",
        "libelleMatiere": "HISTOIRE-GEOGRAPHIE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "14",
        "nonSignificatif": false,
        "date": "2022-11-21",
        "dateSaisie": "2022-11-21",
        "valeurisee": false,
        "moyenneClasse": "15.69",
        "elementsProgramme": []
      },
      {
        "id": 20972746,
        "devoir": "Questionnaire Sports et société",
        "codePeriode": "A001",
        "codeMatiere": "ESP2",
        "libelleMatiere": "ESPAGNOL LV2",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "13,5",
        "nonSignificatif": false,
        "date": "2022-11-21",
        "dateSaisie": "2022-11-21",
        "valeurisee": false,
        "moyenneClasse": "15.07",
        "elementsProgramme": [],
        "qcm": {
          "idQCM": 57,
          "idAssociation": 24,
          "titre": "Deporte y sociedad"
        }
      },
      {
        "id": 20972739,
        "devoir": "DS 1",
        "codePeriode": "A001",
        "codeMatiere": "SNTEC",
        "libelleMatiere": "SC.NUMERIQ.TECHNOL.",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "15",
        "nonSignificatif": false,
        "date": "2022-11-21",
        "dateSaisie": "2022-11-21",
        "valeurisee": false,
        "moyenneClasse": "11.14",
        "elementsProgramme": []
      },
      {
        "id": 20972793,
        "devoir": "Exposé biodiversité",
        "codePeriode": "A001",
        "codeMatiere": "SVT",
        "libelleMatiere": "SCIENCES VIE & TERRE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "15,5",
        "nonSignificatif": false,
        "date": "2022-11-22",
        "dateSaisie": "2022-11-22",
        "valeurisee": false,
        "moyenneClasse": "15.65",
        "elementsProgramme": []
      },
      {
        "id": 20972901,
        "devoir": "DM 3",
        "codePeriode": "A001",
        "codeMatiere": "MATHS",
        "libelleMatiere": "MATHEMATIQUES",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "20",
        "nonSignificatif": false,
        "date": "2022-11-23",
        "dateSaisie": "2022-11-23",
        "valeurisee": false,
        "moyenneClasse": "18.56",
        "elementsProgramme": []
      },
      {
        "id": 20972995,
        "devoir": "Participation",
        "codePeriode": "A001",
        "codeMatiere": "ESP2",
        "libelleMatiere": "ESPAGNOL LV2",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "15",
        "nonSignificatif": false,
        "date": "2022-11-24",
        "dateSaisie": "2022-11-24",
        "valeurisee": false,
        "moyenneClasse": "13.67",
        "elementsProgramme": []
      },
      {
        "id": 20973259,
        "devoir": "Interrogation méthodologie commentaire de texte",
        "codePeriode": "A001",
        "codeMatiere": "FRANC",
        "libelleMatiere": "FRANCAIS",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "18",
        "nonSignificatif": false,
        "date": "2022-11-25",
        "dateSaisie": "2022-11-27",
        "valeurisee": false,
        "moyenneClasse": "18.86",
        "elementsProgramme": []
      },
      {
        "id": 20973208,
        "devoir": "Contrôle de connaissances n°1",
        "codePeriode": "A001",
        "codeMatiere": "SES",
        "libelleMatiere": "SC. ECONO.& SOCIALES",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "12",
        "nonSignificatif": false,
        "date": "2022-11-27",
        "dateSaisie": "2022-11-27",
        "valeurisee": false,
        "moyenneClasse": "11.53",
        "elementsProgramme": []
      },
      {
        "id": 20973211,
        "devoir": "Oral (cc)",
        "codePeriode": "A001",
        "codeMatiere": "SES",
        "libelleMatiere": "SC. ECONO.& SOCIALES",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "10",
        "valeur": "7",
        "nonSignificatif": false,
        "date": "2022-11-27",
        "dateSaisie": "2022-11-27",
        "valeurisee": false,
        "moyenneClasse": "5.99",
        "elementsProgramme": []
      },
      {
        "id": 20973209,
        "devoir": "Oral (interrogation)",
        "codePeriode": "A001",
        "codeMatiere": "SES",
        "libelleMatiere": "SC. ECONO.& SOCIALES",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": true,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "5",
        "valeur": "NE ",
        "nonSignificatif": false,
        "date": "2022-11-27",
        "dateSaisie": "2022-11-27",
        "valeurisee": false,
        "moyenneClasse": "",
        "elementsProgramme": []
      },
      {
        "id": 20973159,
        "devoir": "TP chapitre 3",
        "codePeriode": "A001",
        "codeMatiere": "PH-CH",
        "libelleMatiere": "PHYSIQUE-CHIMIE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "13,5",
        "nonSignificatif": false,
        "date": "2022-11-27",
        "dateSaisie": "2022-11-27",
        "valeurisee": false,
        "moyenneClasse": "16.00",
        "elementsProgramme": []
      },
      {
        "id": 20973157,
        "devoir": "TP 3 chapitre 2",
        "codePeriode": "A001",
        "codeMatiere": "PH-CH",
        "libelleMatiere": "PHYSIQUE-CHIMIE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "20",
        "nonSignificatif": false,
        "date": "2022-11-27",
        "dateSaisie": "2022-11-27",
        "valeurisee": false,
        "moyenneClasse": "18.12",
        "elementsProgramme": []
      },
      {
        "id": 20973973,
        "devoir": "DST / EE",
        "codePeriode": "A002",
        "codeMatiere": "AGL1",
        "libelleMatiere": "ANGLAIS LV1",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "15",
        "nonSignificatif": false,
        "date": "2022-11-29",
        "dateSaisie": "2023-01-02",
        "valeurisee": false,
        "moyenneClasse": "11.40",
        "elementsProgramme": []
      },
      {
        "id": 20973943,
        "devoir": "DST / CE",
        "codePeriode": "A002",
        "codeMatiere": "AGL1",
        "libelleMatiere": "ANGLAIS LV1",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "17",
        "nonSignificatif": false,
        "date": "2022-11-29",
        "dateSaisie": "2023-01-03",
        "valeurisee": false,
        "moyenneClasse": "11.98",
        "elementsProgramme": []
      },
      {
        "id": 20973547,
        "devoir": "IE",
        "codePeriode": "A002",
        "codeMatiere": "MATHS",
        "libelleMatiere": "MATHEMATIQUES",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "10",
        "valeur": "10",
        "nonSignificatif": false,
        "date": "2022-11-30",
        "dateSaisie": "2022-12-08",
        "valeurisee": false,
        "moyenneClasse": "4.56",
        "elementsProgramme": []
      },
      {
        "id": 20973677,
        "devoir": "Interrogation méthodologie ",
        "codePeriode": "A002",
        "codeMatiere": "FRANC",
        "libelleMatiere": "FRANCAIS",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": true,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "Disp ",
        "nonSignificatif": false,
        "date": "2022-12-02",
        "dateSaisie": "2022-12-05",
        "valeurisee": false,
        "moyenneClasse": "",
        "elementsProgramme": []
      },
      {
        "id": 20973675,
        "devoir": "Introduction chapitre 19 de Candide",
        "codePeriode": "A002",
        "codeMatiere": "FRANC",
        "libelleMatiere": "FRANCAIS",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "11,5",
        "nonSignificatif": false,
        "date": "2022-12-02",
        "dateSaisie": "2022-12-05",
        "valeurisee": false,
        "moyenneClasse": "11.25",
        "elementsProgramme": []
      },
      {
        "id": 20973707,
        "devoir": "DST CE Séquence 2 Deporte y sociedad",
        "codePeriode": "A002",
        "codeMatiere": "ESP2",
        "libelleMatiere": "ESPAGNOL LV2",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "14",
        "nonSignificatif": false,
        "date": "2022-12-06",
        "dateSaisie": "2022-12-06",
        "valeurisee": false,
        "moyenneClasse": "15.46",
        "elementsProgramme": []
      },
      {
        "id": 20974274,
        "devoir": "DST Candide de Voltaire",
        "codePeriode": "A002",
        "codeMatiere": "FRANC",
        "libelleMatiere": "FRANCAIS",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "12,5",
        "nonSignificatif": false,
        "date": "2022-12-06",
        "dateSaisie": "2023-01-16",
        "valeurisee": false,
        "moyenneClasse": "10.02",
        "elementsProgramme": []
      },
      {
        "id": 20973708,
        "devoir": "DST EE Séquence 2 Deporte y sociedad",
        "codePeriode": "A002",
        "codeMatiere": "ESP2",
        "libelleMatiere": "ESPAGNOL LV2",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "15",
        "nonSignificatif": false,
        "date": "2022-12-06",
        "dateSaisie": "2022-12-06",
        "valeurisee": false,
        "moyenneClasse": "12.04",
        "elementsProgramme": []
      },
      {
        "id": 20973770,
        "devoir": "Contrôle",
        "codePeriode": "A002",
        "codeMatiere": "PH-CH",
        "libelleMatiere": "PHYSIQUE-CHIMIE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "16",
        "nonSignificatif": false,
        "date": "2022-12-09",
        "dateSaisie": "2022-12-09",
        "valeurisee": false,
        "moyenneClasse": "12.92",
        "elementsProgramme": []
      },
      {
        "id": 20973787,
        "devoir": "Exposé",
        "codePeriode": "A002",
        "codeMatiere": "HI-GE",
        "libelleMatiere": "HISTOIRE-GEOGRAPHIE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "14,5",
        "nonSignificatif": false,
        "date": "2022-12-09",
        "dateSaisie": "2022-12-09",
        "valeurisee": false,
        "moyenneClasse": "15.19",
        "elementsProgramme": []
      },
      {
        "id": 20973809,
        "devoir": "DM 4",
        "codePeriode": "A002",
        "codeMatiere": "MATHS",
        "libelleMatiere": "MATHEMATIQUES",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "20",
        "nonSignificatif": false,
        "date": "2022-12-10",
        "dateSaisie": "2022-12-10",
        "valeurisee": false,
        "moyenneClasse": "15.92",
        "elementsProgramme": []
      },
      {
        "id": 20974276,
        "devoir": "DM Candide",
        "codePeriode": "A002",
        "codeMatiere": "FRANC",
        "libelleMatiere": "FRANCAIS",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": true,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "Disp ",
        "nonSignificatif": false,
        "date": "2022-12-12",
        "dateSaisie": "2023-01-16",
        "valeurisee": false,
        "moyenneClasse": "",
        "elementsProgramme": []
      },
      {
        "id": 20974835,
        "devoir": "Course 1/2 fond",
        "codePeriode": "A002",
        "codeMatiere": "EPS",
        "libelleMatiere": "ED.PHYSIQUE & SPORT.",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "13,5",
        "nonSignificatif": false,
        "date": "2022-12-13",
        "dateSaisie": "2023-02-07",
        "valeurisee": false,
        "moyenneClasse": "14.77",
        "elementsProgramme": []
      },
      {
        "id": 20973951,
        "devoir": "DS ",
        "codePeriode": "A002",
        "codeMatiere": "MATHS",
        "libelleMatiere": "MATHEMATIQUES",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "14",
        "nonSignificatif": false,
        "date": "2022-12-13",
        "dateSaisie": "2023-01-05",
        "valeurisee": false,
        "moyenneClasse": "9.09",
        "elementsProgramme": []
      },
      {
        "id": 20973913,
        "devoir": "Interro figure de style",
        "codePeriode": "A002",
        "codeMatiere": "FRANC",
        "libelleMatiere": "FRANCAIS",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "17,5",
        "nonSignificatif": false,
        "date": "2022-12-13",
        "dateSaisie": "2022-12-16",
        "valeurisee": false,
        "moyenneClasse": "16.07",
        "elementsProgramme": []
      },
      {
        "id": 20974036,
        "devoir": "Contrôle de connaissances séquence 3",
        "codePeriode": "A002",
        "codeMatiere": "ESP2",
        "libelleMatiere": "ESPAGNOL LV2",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "15",
        "nonSignificatif": false,
        "date": "2022-12-15",
        "dateSaisie": "2023-01-05",
        "valeurisee": false,
        "moyenneClasse": "15.12",
        "elementsProgramme": []
      },
      {
        "id": 20973953,
        "devoir": "Oral thèmes 3 et 4",
        "codePeriode": "A002",
        "codeMatiere": "SNTEC",
        "libelleMatiere": "SC.NUMERIQ.TECHNOL.",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "17,5",
        "nonSignificatif": false,
        "date": "2022-12-16",
        "dateSaisie": "2023-01-05",
        "valeurisee": false,
        "moyenneClasse": "15.50",
        "elementsProgramme": []
      },
      {
        "id": 20974240,
        "devoir": "DM Kwyk",
        "codePeriode": "A002",
        "codeMatiere": "PH-CH",
        "libelleMatiere": "PHYSIQUE-CHIMIE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "18",
        "nonSignificatif": false,
        "date": "2023-01-05",
        "dateSaisie": "2023-01-15",
        "valeurisee": false,
        "moyenneClasse": "16.39",
        "elementsProgramme": []
      },
      {
        "id": 20974277,
        "devoir": "Rédaction (DM)",
        "codePeriode": "A002",
        "codeMatiere": "FRANC",
        "libelleMatiere": "FRANCAIS",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "12,5",
        "nonSignificatif": false,
        "date": "2023-01-05",
        "dateSaisie": "2023-01-16",
        "valeurisee": false,
        "moyenneClasse": "12.28",
        "elementsProgramme": []
      },
      {
        "id": 20974958,
        "devoir": "Dictée",
        "codePeriode": "A002",
        "codeMatiere": "FRANC",
        "libelleMatiere": "FRANCAIS",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "18",
        "nonSignificatif": false,
        "date": "2023-01-06",
        "dateSaisie": "2023-02-12",
        "valeurisee": false,
        "moyenneClasse": "15.08",
        "elementsProgramme": []
      },
      {
        "id": 20974241,
        "devoir": "Interrogation Kwyk",
        "codePeriode": "A002",
        "codeMatiere": "PH-CH",
        "libelleMatiere": "PHYSIQUE-CHIMIE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "19",
        "nonSignificatif": false,
        "date": "2023-01-06",
        "dateSaisie": "2023-01-14",
        "valeurisee": false,
        "moyenneClasse": "15.14",
        "elementsProgramme": []
      },
      {
        "id": 20974280,
        "devoir": "TP chapitre 14",
        "codePeriode": "A002",
        "codeMatiere": "PH-CH",
        "libelleMatiere": "PHYSIQUE-CHIMIE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "19",
        "nonSignificatif": false,
        "date": "2023-01-09",
        "dateSaisie": "2023-01-16",
        "valeurisee": false,
        "moyenneClasse": "16.36",
        "elementsProgramme": []
      },
      {
        "id": 20974425,
        "devoir": "IE",
        "codePeriode": "A002",
        "codeMatiere": "MATHS",
        "libelleMatiere": "MATHEMATIQUES",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "16,5",
        "nonSignificatif": false,
        "date": "2023-01-12",
        "dateSaisie": "2023-01-21",
        "valeurisee": false,
        "moyenneClasse": "12.97",
        "elementsProgramme": []
      },
      {
        "id": 20974329,
        "devoir": "DS",
        "codePeriode": "A002",
        "codeMatiere": "SNTEC",
        "libelleMatiere": "SC.NUMERIQ.TECHNOL.",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "17,5",
        "nonSignificatif": false,
        "date": "2023-01-12",
        "dateSaisie": "2023-01-19",
        "valeurisee": false,
        "moyenneClasse": "15.97",
        "elementsProgramme": []
      },
      {
        "id": 20974278,
        "devoir": "Interrogation Phèdre",
        "codePeriode": "A002",
        "codeMatiere": "FRANC",
        "libelleMatiere": "FRANCAIS",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "17,5",
        "nonSignificatif": false,
        "date": "2023-01-13",
        "dateSaisie": "2023-01-16",
        "valeurisee": false,
        "moyenneClasse": "18.43",
        "elementsProgramme": []
      },
      {
        "id": 20974570,
        "devoir": "DST n° 2",
        "codePeriode": "A002",
        "codeMatiere": "PH-CH",
        "libelleMatiere": "PHYSIQUE-CHIMIE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "19,5",
        "nonSignificatif": false,
        "date": "2023-01-17",
        "dateSaisie": "2023-01-27",
        "valeurisee": false,
        "moyenneClasse": "12.66",
        "elementsProgramme": []
      },
      {
        "id": 20974314,
        "devoir": "Las Casas",
        "codePeriode": "A002",
        "codeMatiere": "HI-GE",
        "libelleMatiere": "HISTOIRE-GEOGRAPHIE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "11",
        "nonSignificatif": false,
        "date": "2023-01-17",
        "dateSaisie": "2023-01-17",
        "valeurisee": false,
        "moyenneClasse": "12.04",
        "elementsProgramme": []
      },
      {
        "id": 20974430,
        "devoir": "Évaluation Chapitre 2",
        "codePeriode": "A002",
        "codeMatiere": "SES",
        "libelleMatiere": "SC. ECONO.& SOCIALES",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "16",
        "nonSignificatif": false,
        "date": "2023-01-20",
        "dateSaisie": "2023-01-20",
        "valeurisee": false,
        "moyenneClasse": "13.47",
        "elementsProgramme": []
      },
      {
        "id": 20974433,
        "devoir": "DST n°1",
        "codePeriode": "A002",
        "codeMatiere": "SES",
        "libelleMatiere": "SC. ECONO.& SOCIALES",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "11",
        "nonSignificatif": false,
        "date": "2023-01-20",
        "dateSaisie": "2023-01-20",
        "valeurisee": false,
        "moyenneClasse": "10.65",
        "elementsProgramme": []
      },
      {
        "id": 20974413,
        "devoir": "TP sélection naturelle",
        "codePeriode": "A002",
        "codeMatiere": "SVT",
        "libelleMatiere": "SCIENCES VIE & TERRE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "15",
        "valeur": "13",
        "nonSignificatif": false,
        "date": "2023-01-20",
        "dateSaisie": "2023-01-24",
        "valeurisee": false,
        "moyenneClasse": "10.62",
        "elementsProgramme": []
      },
      {
        "id": 20974652,
        "devoir": "CO Home Planet",
        "codePeriode": "A002",
        "codeMatiere": "AGL1",
        "libelleMatiere": "ANGLAIS LV1",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "19",
        "nonSignificatif": false,
        "date": "2023-01-23",
        "dateSaisie": "2023-01-31",
        "valeurisee": false,
        "moyenneClasse": "16.87",
        "elementsProgramme": []
      },
      {
        "id": 20974526,
        "devoir": "DM 5",
        "codePeriode": "A002",
        "codeMatiere": "MATHS",
        "libelleMatiere": "MATHEMATIQUES",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "20",
        "nonSignificatif": false,
        "date": "2023-01-26",
        "dateSaisie": "2023-01-26",
        "valeurisee": false,
        "moyenneClasse": "18.81",
        "elementsProgramme": []
      },
      {
        "id": 20974959,
        "devoir": "DST Phèdre de Racine ",
        "codePeriode": "A002",
        "codeMatiere": "FRANC",
        "libelleMatiere": "FRANCAIS",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "11",
        "nonSignificatif": false,
        "date": "2023-01-27",
        "dateSaisie": "2023-02-12",
        "valeurisee": false,
        "moyenneClasse": "10.83",
        "elementsProgramme": []
      },
      {
        "id": 20974960,
        "devoir": "DM Phèdre rattrapage ",
        "codePeriode": "A002",
        "codeMatiere": "FRANC",
        "libelleMatiere": "FRANCAIS",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": true,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "NE ",
        "nonSignificatif": false,
        "date": "2023-01-30",
        "dateSaisie": "2023-02-12",
        "valeurisee": false,
        "moyenneClasse": "",
        "elementsProgramme": []
      },
      {
        "id": 20975425,
        "devoir": "DST EE Séquence 3 Creación y arte",
        "codePeriode": "A002",
        "codeMatiere": "ESP2",
        "libelleMatiere": "ESPAGNOL LV2",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "13",
        "nonSignificatif": false,
        "date": "2023-01-31",
        "dateSaisie": "2023-03-08",
        "valeurisee": false,
        "moyenneClasse": "12.31",
        "elementsProgramme": []
      },
      {
        "id": 20974669,
        "devoir": "Débat",
        "codePeriode": "A002",
        "codeMatiere": "HI-GE",
        "libelleMatiere": "HISTOIRE-GEOGRAPHIE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "10",
        "valeur": "7",
        "nonSignificatif": false,
        "date": "2023-02-01",
        "dateSaisie": "2023-02-01",
        "valeurisee": false,
        "moyenneClasse": "8.39",
        "elementsProgramme": []
      },
      {
        "id": 20974764,
        "devoir": "DST QCM",
        "codePeriode": "A002",
        "codeMatiere": "SVT",
        "libelleMatiere": "SCIENCES VIE & TERRE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "10",
        "valeur": "9",
        "nonSignificatif": false,
        "date": "2023-02-06",
        "dateSaisie": "2023-02-07",
        "valeurisee": false,
        "moyenneClasse": "7.54",
        "elementsProgramme": []
      },
      {
        "id": 20975543,
        "devoir": "DM Phèdre",
        "codePeriode": "A002",
        "codeMatiere": "FRANC",
        "libelleMatiere": "FRANCAIS",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "13,5",
        "nonSignificatif": false,
        "date": "2023-02-06",
        "dateSaisie": "2023-03-10",
        "valeurisee": false,
        "moyenneClasse": "11.33",
        "elementsProgramme": []
      },
      {
        "id": 20975257,
        "devoir": "EE Canadian Mosaic",
        "codePeriode": "A002",
        "codeMatiere": "AGL1",
        "libelleMatiere": "ANGLAIS LV1",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "16",
        "nonSignificatif": false,
        "date": "2023-02-10",
        "dateSaisie": "2023-02-24",
        "valeurisee": false,
        "moyenneClasse": "14.83",
        "elementsProgramme": []
      },
      {
        "id": 20974961,
        "devoir": "Poésie sur Phèdre",
        "codePeriode": "A002",
        "codeMatiere": "FRANC",
        "libelleMatiere": "FRANCAIS",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "15",
        "nonSignificatif": false,
        "date": "2023-02-10",
        "dateSaisie": "2023-02-12",
        "valeurisee": false,
        "moyenneClasse": "13.83",
        "elementsProgramme": []
      },
      {
        "id": 20975255,
        "devoir": "CO Canadian Mosaïc",
        "codePeriode": "A002",
        "codeMatiere": "AGL1",
        "libelleMatiere": "ANGLAIS LV1",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "18",
        "nonSignificatif": false,
        "date": "2023-02-13",
        "dateSaisie": "2023-02-24",
        "valeurisee": false,
        "moyenneClasse": "15.43",
        "elementsProgramme": []
      },
      {
        "id": 20975624,
        "devoir": "TP chapitre 7",
        "codePeriode": "A002",
        "codeMatiere": "PH-CH",
        "libelleMatiere": "PHYSIQUE-CHIMIE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "18,5",
        "nonSignificatif": false,
        "date": "2023-02-13",
        "dateSaisie": "2023-03-10",
        "valeurisee": false,
        "moyenneClasse": "16.85",
        "elementsProgramme": []
      },
      {
        "id": 20975649,
        "devoir": "Badminton",
        "codePeriode": "A002",
        "codeMatiere": "EPS",
        "libelleMatiere": "ED.PHYSIQUE & SPORT.",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "13,5",
        "nonSignificatif": false,
        "date": "2023-02-14",
        "dateSaisie": "2023-03-11",
        "valeurisee": false,
        "moyenneClasse": "14.17",
        "elementsProgramme": []
      },
      {
        "id": 20975086,
        "devoir": "informatique",
        "codePeriode": "A002",
        "codeMatiere": "MATHS",
        "libelleMatiere": "MATHEMATIQUES",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "15",
        "nonSignificatif": false,
        "date": "2023-02-15",
        "dateSaisie": "2023-02-17",
        "valeurisee": false,
        "moyenneClasse": "12.29",
        "elementsProgramme": []
      },
      {
        "id": 20975074,
        "devoir": "test calcul",
        "codePeriode": "A002",
        "codeMatiere": "MATHS",
        "libelleMatiere": "MATHEMATIQUES",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "15",
        "nonSignificatif": false,
        "date": "2023-02-15",
        "dateSaisie": "2023-02-17",
        "valeurisee": false,
        "moyenneClasse": "8.21",
        "elementsProgramme": []
      },
      {
        "id": 20975075,
        "devoir": "DM 6",
        "codePeriode": "A002",
        "codeMatiere": "MATHS",
        "libelleMatiere": "MATHEMATIQUES",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "20",
        "nonSignificatif": false,
        "date": "2023-02-15",
        "dateSaisie": "2023-02-15",
        "valeurisee": false,
        "moyenneClasse": "18.37",
        "elementsProgramme": []
      },
      {
        "id": 20975067,
        "devoir": "DST Etude de docs",
        "codePeriode": "A002",
        "codeMatiere": "SVT",
        "libelleMatiere": "SCIENCES VIE & TERRE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "10",
        "valeur": "7,75",
        "nonSignificatif": false,
        "date": "2023-02-15",
        "dateSaisie": "2023-02-18",
        "valeurisee": false,
        "moyenneClasse": "6.36",
        "elementsProgramme": []
      },
      {
        "id": 20975166,
        "devoir": "DS",
        "codePeriode": "A002",
        "codeMatiere": "HI-GE",
        "libelleMatiere": "HISTOIRE-GEOGRAPHIE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "11",
        "nonSignificatif": false,
        "date": "2023-02-17",
        "dateSaisie": "2023-02-17",
        "valeurisee": false,
        "moyenneClasse": "11.67",
        "elementsProgramme": []
      },
      {
        "id": 20975534,
        "devoir": "ORAUX ",
        "codePeriode": "A002",
        "codeMatiere": "FRANC",
        "libelleMatiere": "FRANCAIS",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "14",
        "nonSignificatif": false,
        "date": "2023-03-06",
        "dateSaisie": "2023-03-09",
        "valeurisee": false,
        "moyenneClasse": "14.44",
        "elementsProgramme": []
      },
      {
        "id": 20975416,
        "devoir": "Oraux",
        "codePeriode": "A002",
        "codeMatiere": "SES",
        "libelleMatiere": "SC. ECONO.& SOCIALES",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "10",
        "valeur": "7,5",
        "nonSignificatif": false,
        "date": "2023-03-07",
        "dateSaisie": "2023-03-07",
        "valeurisee": false,
        "moyenneClasse": "7.39",
        "elementsProgramme": []
      },
      {
        "id": 36,
        "devoir": "Evaluation CNED",
        "codePeriode": "A002",
        "codeMatiere": "ITA3H",
        "libelleMatiere": "ITALIEN LV3 HOR.ETAB",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "20",
        "nonSignificatif": false,
        "date": "2023-03-07",
        "dateSaisie": "2023-03-07",
        "valeurisee": false,
        "moyenneClasse": "20.00",
        "elementsProgramme": []
      },
      {
        "id": 20975623,
        "devoir": "Oral",
        "codePeriode": "A002",
        "codeMatiere": "PH-CH",
        "libelleMatiere": "PHYSIQUE-CHIMIE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "17",
        "nonSignificatif": false,
        "date": "2023-03-07",
        "dateSaisie": "2023-03-10",
        "valeurisee": false,
        "moyenneClasse": "12.88",
        "elementsProgramme": []
      },
      {
        "id": 20975427,
        "devoir": "Contrôles divers (grammaire et orthographe)",
        "codePeriode": "A002",
        "codeMatiere": "ESP2",
        "libelleMatiere": "ESPAGNOL LV2",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "15,5",
        "nonSignificatif": false,
        "date": "2023-03-08",
        "dateSaisie": "2023-03-08",
        "valeurisee": false,
        "moyenneClasse": "12.75",
        "elementsProgramme": []
      },
      {
        "id": 20975423,
        "devoir": "DST CE Séquence 3 Creación y arte",
        "codePeriode": "A002",
        "codeMatiere": "ESP2",
        "libelleMatiere": "ESPAGNOL LV2",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "17",
        "nonSignificatif": false,
        "date": "2023-03-08",
        "dateSaisie": "2023-03-08",
        "valeurisee": false,
        "moyenneClasse": "14.62",
        "elementsProgramme": []
      },
      {
        "id": 20975421,
        "devoir": "EE Projet final séquence 3 Creación y arte",
        "codePeriode": "A002",
        "codeMatiere": "ESP2",
        "libelleMatiere": "ESPAGNOL LV2",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "16",
        "nonSignificatif": false,
        "date": "2023-03-08",
        "dateSaisie": "2023-03-08",
        "valeurisee": false,
        "moyenneClasse": "13.56",
        "elementsProgramme": []
      },
      {
        "id": 20975471,
        "devoir": "Oral SVT",
        "codePeriode": "A002",
        "codeMatiere": "SVT",
        "libelleMatiere": "SCIENCES VIE & TERRE",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "16",
        "nonSignificatif": false,
        "date": "2023-03-09",
        "dateSaisie": "2023-03-09",
        "valeurisee": false,
        "moyenneClasse": "13.31",
        "elementsProgramme": []
      },
      {
        "id": 20975610,
        "devoir": "Participation orale en classe",
        "codePeriode": "A002",
        "codeMatiere": "ESP2",
        "libelleMatiere": "ESPAGNOL LV2",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "13",
        "nonSignificatif": false,
        "date": "2023-03-10",
        "dateSaisie": "2023-03-10",
        "valeurisee": false,
        "moyenneClasse": "14.80",
        "elementsProgramme": []
      },
      {
        "id": 20975633,
        "devoir": "Oral cc",
        "codePeriode": "A002",
        "codeMatiere": "SES",
        "libelleMatiere": "SC. ECONO.& SOCIALES",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": true,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "5",
        "valeur": "NE ",
        "nonSignificatif": false,
        "date": "2023-03-11",
        "dateSaisie": "2023-03-11",
        "valeurisee": false,
        "moyenneClasse": "",
        "elementsProgramme": []
      },
      {
        "id": 20975721,
        "devoir": "Carnet de voyage Candide de Voltaire",
        "codePeriode": "A002",
        "codeMatiere": "FRANC",
        "libelleMatiere": "FRANCAIS",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "15",
        "nonSignificatif": false,
        "date": "2023-03-12",
        "dateSaisie": "2023-03-12",
        "valeurisee": false,
        "moyenneClasse": "14.15",
        "elementsProgramme": []
      },
      {
        "id": 20976036,
        "devoir": "Interrogation sur l'Etranger de Camus",
        "codePeriode": "A003",
        "codeMatiere": "FRANC",
        "libelleMatiere": "FRANCAIS",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": false,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "17",
        "nonSignificatif": false,
        "date": "2023-03-13",
        "dateSaisie": "2023-03-20",
        "valeurisee": false,
        "moyenneClasse": "15.54",
        "elementsProgramme": []
      },
      {
        "id": 20976035,
        "devoir": "ORAUX rattrapage ",
        "codePeriode": "A003",
        "codeMatiere": "FRANC",
        "libelleMatiere": "FRANCAIS",
        "codeSousMatiere": "",
        "typeDevoir": "",
        "enLettre": true,
        "commentaire": "",
        "uncSujet": "",
        "uncCorrige": "",
        "coef": 0,
        "noteSur": "20",
        "valeur": "NE ",
        "nonSignificatif": false,
        "date": "2023-03-13",
        "dateSaisie": "2023-03-20",
        "valeurisee": false,
        "moyenneClasse": "",
        "elementsProgramme": []
      }
    ],
  };
}



